name: "1. Code Checks (CI)"

on: [push]  # change to [push] to enable CI on every push

jobs:
  code-checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Lint with pylint
        run: pylint src/data.py src/train.py --fail-under=7.0 --disable=C0114,C0115,C0116

      - name: Run unit tests
        run: pytest tests/test_code.py -v
